### ISSUE TITLE
Negative ctez balance after oven liquidation

### ISSUE THREAD

**Issue by baketzforme** [Tezsure/ctez#113]
I'm not sure if this is an issue with the ctez contracts or an indexing issue with wallets and block explorers, but an account is showing a negative balance of ctez even though it actually has a positive balance.

TzKT is showing [this account](https://tzkt.io/tz1S91vGGRnvezkDddwwsnHuKezstTgoHWwc/tokens) as having about `-1743` ctez.

The actual balance is about `87.5` ctez according to DEXes such as QuipuSwap or even ctez.app's swap page.

About [`1831.45` ctez were liquidated](https://tzkt.io/oo69qpFHamnTnMKtMuJmCYV8CkZkudD8UADQPt11d5YUqEe4nV8) from the account's oven.

`-1,831.45 + 87.5 ≈ -1,743`

It appears as though the ctez burned during the liquidation event is not properly accounted for when displaying the balance of tokens in the account. TzKT shows a negative balance. Kukai and TzStats don't list the ctez at all. Presumably they just don't display tokens balances that are near or below 0.

What can be done to get the correct balance of ctez to show in wallets and on block explorers?

**Comment by malviyaop** [comment]
I think it might have to do more with how tzkt indexes the data. 

We will look into tzstats and kukai indexing  issue though.

**Comment by malviyaop** [comment]
*Tzkt indexes the balances of ctez
