### ISSUE TITLE
Inaccurate weekly drift

### ISSUE THREAD

**Issue by murbard** [Tezsure/ctez#117]
The weekly drift's computation is inaccurate but also needlessly complicated. Currently, it tries to find the last back block before midnight 7 days in the past, which means the actual time period varies between 6 * 24 hours and 7 * 24 hours, even though the drift is then normalized assuming 7 * 24 hours. 

Instead, a simple solution is to take the minimum block time (30 seconds), go back 20,160 blocks in the past, request this block. It will generally not give exactly a week, but looking at the timestamp of that block, it's possible to measure exactly how much time elapsed during those 20,160 blocks  and then measure `(target / old_target)^(365.25 * 24 * 3600) / (timestamp_of_last_block - time_stamp_of_block_20160_blocks ago))`. It won't always be precisely a week, but that doesn't matter, what matter is that the drift itself be precise.

Alternatively, the measure could be dropped altogether, it's not that useful.

**Comment by berndoostrum** [comment]
Removed weekly drift
